// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHmIJwBojgk5lJHhoxWUtxSmq9nLsdMas',
    appId: '1:965640393594:web:2aa53256eac0c0a14efcc3',
    messagingSenderId: '965640393594',
    projectId: 'mhdsapp',
    authDomain: 'mhdsapp.firebaseapp.com',
    storageBucket: 'mhdsapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLP2BF-U0FmE_ebBzlUx4tjijgJ-bT-To',
    appId: '1:965640393594:android:66a1fc5c11ff3b5f4efcc3',
    messagingSenderId: '965640393594',
    projectId: 'mhdsapp',
    storageBucket: 'mhdsapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdWq8FYPygrH7T-Pw1dQ49rPXkEpvMO74',
    appId: '1:965640393594:ios:b12fc769a07d933e4efcc3',
    messagingSenderId: '965640393594',
    projectId: 'mhdsapp',
    storageBucket: 'mhdsapp.appspot.com',
    iosBundleId: 'com.example.metalHealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdWq8FYPygrH7T-Pw1dQ49rPXkEpvMO74',
    appId: '1:965640393594:ios:b12fc769a07d933e4efcc3',
    messagingSenderId: '965640393594',
    projectId: 'mhdsapp',
    storageBucket: 'mhdsapp.appspot.com',
    iosBundleId: 'com.example.metalHealth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHmIJwBojgk5lJHhoxWUtxSmq9nLsdMas',
    appId: '1:965640393594:web:fa1ad11abd01f1234efcc3',
    messagingSenderId: '965640393594',
    projectId: 'mhdsapp',
    authDomain: 'mhdsapp.firebaseapp.com',
    storageBucket: 'mhdsapp.appspot.com',
  );
}
